In [48]:
import numpy as np


arr = np.arange(1,101).reshape(10,10)

arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [6]:
arr[-5:,-5:]

array([[ 56,  57,  58,  59,  60],
       [ 66,  67,  68,  69,  70],
       [ 76,  77,  78,  79,  80],
       [ 86,  87,  88,  89,  90],
       [ 96,  97,  98,  99, 100]])

In [7]:
arr[-5:,-5:].flatten() + 5

array([ 61,  62,  63,  64,  65,  71,  72,  73,  74,  75,  81,  82,  83,
        84,  85,  91,  92,  93,  94,  95, 101, 102, 103, 104, 105])

In [8]:
np.median(arr[-5:,-5:].flatten() + 5)

83.0

In [23]:
import pandas as pd

pd = pd.read_csv("C:\\Moiyyad\\STAT5400 STAT Computing\\hw.10\\ml-100k (1)\\ml-100k\\u.item", delimiter='|',  encoding='latin-1')

pd.head(5)

1                                   Toy Story (1995)  01-Jan-1995  \
0  2                                   GoldenEye (1995)  01-Jan-1995   
1  3                                  Four Rooms (1995)  01-Jan-1995   
2  4                                  Get Shorty (1995)  01-Jan-1995   
3  5                                     Copycat (1995)  01-Jan-1995   
4  6  Shanghai Triad (Yao a yao yao dao waipo qiao) ...  01-Jan-1995   

   Unnamed: 3 http://us.imdb.com/M/title-exact?Toy%20Story%20(1995)  0  0.1  \
0         NaN  http://us.imdb.com/M/title-exact?GoldenEye%20(...     0    1   
1         NaN  http://us.imdb.com/M/title-exact?Four%20Rooms%...     0    0   
2         NaN  http://us.imdb.com/M/title-exact?Get%20Shorty%...     0    1   
3         NaN  http://us.imdb.com/M/title-exact?Copycat%20(1995)     0    0   
4         NaN  http://us.imdb.com/Title?Yao+a+yao+yao+dao+wai...     0    0   

   0.2  1.1  1.2  ...  0.6  0.7  0.8  0.9  0.10  0.11  0.12  0.13  0.14  0.15  
0    1    0    0  ...    0    0    0    0     0     0     0     1     0     0  
1    0    0    0  ...    0    0    0    0     0     0     0     1     0     0  
2    0    0    0  ...    0    0    0    0     0     0     0     0     0     0  
3    0    0    0  ...    0    0    0    0     0     0     0     1     0     0  
4    0    0    0  ...    0    0    0    0     0     0     0     0     0     0  

[5 rows x 24 columns]

In [24]:
pd = pd.drop(['1'], axis=1)
pd = pd.drop(pd.columns[3], axis=1)


pd.head(5)


Toy Story (1995)  01-Jan-1995  Unnamed: 3  \
0                                   GoldenEye (1995)  01-Jan-1995         NaN   
1                                  Four Rooms (1995)  01-Jan-1995         NaN   
2                                  Get Shorty (1995)  01-Jan-1995         NaN   
3                                     Copycat (1995)  01-Jan-1995         NaN   
4  Shanghai Triad (Yao a yao yao dao waipo qiao) ...  01-Jan-1995         NaN   

   0  0.1  0.2  1.1  1.2  1.3  0.3  ...  0.6  0.7  0.8  0.9  0.10  0.11  0.12  \
0  0    1    1    0    0    0    0  ...    0    0    0    0     0     0     0   
1  0    0    0    0    0    0    0  ...    0    0    0    0     0     0     0   
2  0    1    0    0    0    1    0  ...    0    0    0    0     0     0     0   
3  0    0    0    0    0    0    1  ...    0    0    0    0     0     0     0   
4  0    0    0    0    0    0    0  ...    0    0    0    0     0     0     0   

   0.13  0.14  0.15  
0     1     0     0  
1     1     0     0  
2     0     0     0  
3     1     0     0  
4     0     0     0  

[5 rows x 22 columns]

In [57]:

pd['new_col'] = np.sum(pd[pd.columns[-19:]], axis=1)

pd['new_col'].describe()

count    1681.000000
mean       12.027365
std         6.084756
min         1.000000
25%         7.000000
50%        14.000000
75%        14.000000
max        42.000000
Name: new_col, dtype: float64